### ISSUE TITLE
microg lineage builds don't pass safetynet

### ISSUE THREAD

**Issue by montvid** [microg/RemoteDroidGuard#17]
Could someone fix the microg lineage builds to pass safetynet? Now I need to root lineage and copy the apk to /system/priv-app/ myself and then unroot it to pass.

**Comment by ale5000-git** [comment]
You can also use my [microG unofficial installer](https://forum.xda-developers.com/showthread.php?t=3432360) (or other installers) to place the file without root.

**Comment by montvid** [comment]
Thanks, I used twrp file manager to copy the file. Also is there a possibility to increase the widevine security level from L3 to L1? I thought it has something to do with safetynet but now I pass it but drm info shows L3 still.

**Comment by ArchangeGabriel** [comment]
@montvid: Widewine security level is mostly device dependent AFAIK. For example OnePlus started to ask people to send their OnePlus 5T back to them if they wanted the security level to be raised from L3 to L1, because apparently they have to modify things on the device in a way they cannot share. So a first good question would be: does your device reach L1 with vendor OS?

Regarding DroidGuard being placed in /system/priv-app in Lineage4μG, I’m opening an issue for that.

**Comment by montvid** [comment]
Nexus 7 2013 flo does have L1 hdcp 2.2 on stock Android 6 with an unlocked bootloader according to drm info app. How to have L1 on a custom rom I don't know if it is possible.

**Comment by ale5000-git** [comment]
@montvid: Does it have L1 by using official "standard" LineageOS + Open GApps?

If not, then it isn't a microG problem and you should report it to LineageOS.

**Comment by montvid** [comment]
@ale safetynet is not working on lineageos too but microg fixed that. All custom roms I know have L3. Safetynet is a security feature as widevine L1. I am just asking as microg fixed safetynet can the guys fix videwine too.

**Comment by ale5000-git** [comment]
@montvid: Probably the maintainer of your device broke SafetyNet, microG doesn't fix it.

**Comment by mirh** [comment]
> safetynet is not working on lineageos too but microg fixed that

Isn't that the opposite.. of the thread title?

**Comment by Milliw** [comment]
I am also having issues for now regarding this. Wanted to install an app that uses SaftetyNet but was not successful. So I downloaded newest version of droidguard on F-Droid but that didn't solve the issue. Next I found this thread here and made droidguard an system app (by using YALP store function) but still can't pass the SafetyNet check app though MicroG says it is enabled.

Where's the mistake?
I now that it was working when I installed and configured LineageOS at first on my Z3 Compact. Don't know when I lost this.

**Comment by ArchangeGabriel** [comment]
@MarcoWilli No mistake on your side, read from https://github.com/microg/android_packages_apps_GmsCore/issues/482#issuecomment-379681892.

**Comment by Milliw** [comment]
Thanks for that hint. I guess I was looking in the wrong repository. This also explains why there are only three open issues :D
So is my issue really because of this? On PlayStore and Aptoide I can download the app but it just fails because of "not compatible". YALP Store is telling this directly and won't let me download.

Tell me if this is the wrong place for finding a solution/workaround. =)

**Comment by ArchangeGabriel** [comment]
We would need a logcat to know if broken SafetyNet is your issue. If so, they are only two options if you want SafetyNet working: wait for @mar-v-in to come with a fix for it or go back to standard GApps (well technically you can reduce that to PlayServices only).

**Comment by Milliw** [comment]
Thanks again. I was able to solve it on my own with your hint to use logcat. It was because of missing gmaps v1 api. First installed the 0.5 release from your repo but that was not fully working. Then pulled the latest release from microg repo and that did the job. Wasn't able to use the latest committed version because installation instructions are missing but that's another story =)

**Comment by Nanolx** [comment]
@ale5000-git could you close this issue? It's about the old bug fixed by https://github.com/microg/android_packages_apps_RemoteDroidGuard/pull/19

**Comment by ale5000-git** [comment]
@montvid 
I'm closing it since now safetynet is completely broken due to a Google change, once issue #24 is fixed you can open another issue if something is not working for you.
