### ISSUE TITLE
SafetyNet now fails again

### ISSUE THREAD

**Issue by OrionMoonclaw** [microg/RemoteDroidGuard#24]
Google seems to have pushed out an update to SafetyNet that breaks it on MicroG

**Comment by SoaringLake** [comment]
Please, fix it, no safetynet android does not make sense :'(

**Comment by Exodusnick** [comment]
Please, fix it.

**Comment by JohnGLFour** [comment]
@mar-v-in @ThibG 
The problem is how it works, not detect.

**Comment by ClearlyClaire** [comment]
I am aware. I do not know why it fails. And as you may know, DroidGuard is purposefully difficult to understand. I have no time to spend on this for the moment.

**Comment by JohnGLFour** [comment]
@ThibG
Google rewrote the process of how Safetynet works on a new update. @Nanolx mentioned this in his Nanodroid XDA Post.

Take your time, hope you can figure it out.

**Comment by TeslaBargain** [comment]
So SafetyNet still not working?

I just tried with a fresh installation of LineageOS 16.0 MicroG + latest Magisk on my OnePlus 6, installed DroidGuard using F-Droid (I didn't manage to copy it to /system/priv-app though), DroidGuard is selected in Magisk Hide, and the SafetyNet test fails (ctsProfile: false & basicIntegrity: false). Obviously my Internet bank app fails to start.

**Comment by JohnGLFour** [comment]
Obviously, due to a new update Google rewrote how it works to Safetynet, it still not working.

**Comment by Pinjontall94** [comment]
Is there somewhere we can look to help out? Even if it's just bug testing, I'd love to help get this fixed sooner rather than later.

**Comment by Nanolx** [comment]
Not actually. it's on mar-v-in's agenda, but no ETA.

**Comment by smnthermes** [comment]
Don't be tracked, pay cash.

**Comment by Foorack** [comment]
@samantohermes Unserious comment, impractical approach.

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
Any updates on this situation?

**Comment by ghost** [comment]
It would be great to know if this issue is known by now and if it'll get fixed or not.

**Comment by errorcodevortex** [comment]
Any luck here yet? Havoc OS LGV30 tried nanodroid and magisk module going to try manual install from frdroid and systemizer possibly bitgapps. Custom droidguard app from link above 404

**Comment by errorcodevortex** [comment]
I managed to pass both safetynet checks with micro-g everything working atleast for past 4 days. Wasn't to exhaustive but did require fxamework. Not sure if anything can be worked in officially from this angle but I hope. Pm'd Setialpha + Mar-V-in on xda, not sure who else to let know.

**Comment by ghost** [comment]
> but did require fxamework

That's the problem. I suppose you used the HiddenCore Module and yes while it passes SafetyNET most apps that block devices without SafetyNET check will still block you out.

**Comment by errorcodevortex** [comment]
I did have to restore snapchat from Titanium still. Just about everything else working without restore pubg, paypal, maps, my bank app not sure if this is new or not. Only apps that check for x arn't working initially(snap, I guess some high end bank apps, nfc maybe?). Confirmed working on Note 9 and LGV30 roms with pie. Didn't use HiddenCore found a different module did not know about that one but I guess I  should  try that and see what happens with it, if does something different. Was not aware anyone was able to pass safetynet whatsoever yet.

**Comment by ghost** [comment]
> I did have to restore snapchat from Titanium still.

Ye I would like to use that as well again but I don't have a backup...

**Comment by errorcodevortex** [comment]
I flashed again with bitgapps real quick just to make a backup earlier and reflashed everything again myself. But I'm a flashaholic, never get very attached, should be possible to make one from another device as well, would have done that but my x86 build doesn't pass safetynet and the backup phone has ubports on it, thought to maybe try it on anbox but didn't want to install it again didn't know if it would work.

**Comment by ghost** [comment]
I don't really wanna flash again after just setting everything up. And sadly enough I don't have another rooted phone I could use to create a backup :/

**Comment by ghost** [comment]
Likewise, I'd like to emulate it into working somehow. I've even got twrp backups but I am not sure how to extract the right data.

**Comment by errorcodevortex** [comment]
Snapchats not really that great imo, that is tragic tho, I do hate reflashing too for 1 small thing like that. Did get it working with but restore was a bit fidgitty installed apk from store first then restored the data on top of it.

Did have a moment to try out hiddencore 1.7. Don't know how I didn't come across it before. It does seem to work for most apps in the same fashion but my screen display does stays on, read in a thread that it is like that for everyone. It seems many are worried it's also untrustworthy, some going as far to say it somehow "silently infiltrated xda". Personally I couldn't say if there is actually anything adherently wrong with it or unsafe some are saying its not connected to internet at all. Should have checked my list of system apps before not 100% sure if anything else gets installed with either. 

This is the module I chanced across 
 https://drive.google.com/file/d/1kAEBmqd9DB7HCAaIepfqJ_nTtthVkOeY/view?usp=sharing
It is called "safetynet by bdoel" , its package name is com.safetynet.bypass
I was sleuthing on youtube and happened to find a video in a foreign to me language that had a link in it, tried it and it worked. Edit: Found the video again https://www.youtube.com/watch?v=hINBMZq7Hf8&t=26s
Honestly not sure which is more trustworthy, maybe someone can break it down more than I can. Bdoels module seems a good amount smaller 46kb not activated and 160kb activated compared to hiddencore not activated 455kb, so I think it may be less capable of harm and might do less negative or unnecessary things to your system. It also does not effect my screen display(which did sketch me out a bit, not sure if yours stayed on also or you fixed AON somehow) so I think it might be the best fix available right now. Discovered both do not pass with playstore safetynet checkers besides magisk's but I am assuming that is because of signature spoofing permission doing its thing because I don't seem to be facing any safetynet specific issues.

I wanted to try to avoid checks using Tai-chi magisk xposed but I am facing engine error(I guess cuz of edframeworks but not sure what framework is proper), anyone try this? So I am guessing no known rootcloak, suhide, no device check modules or alternatives working anymore?

**Comment by ghost** [comment]
I tried different ways to bypass it (mainly for Snapchat). They nearly all passed Magisk SafetyNET test but still failed with Snapchat what is quite sad because Snapchat only checks for SafetyNET before login in. Since I don't have a file backup that doesn't help me though

**Comment by jeroenev** [comment]
any updates on this?
bypass possible without xposed? don't want to root my device.
also doubt that com.safetynet.bypass is open source

**Comment by ghost** [comment]
Even with Xposed it's not easy to trick the Safetynet check. So no without root you won't get anywhere but also with it doesn't help a lot. I guess we just gotta wait till they drop an update for MicroG

**Comment by errorcodevortex** [comment]
I don't think either fix is fully open source. I do though think it makes a big difference tho, helps a lot. Passing both checks as opposed to failing them both. Seemed pretty easy. I don't use google pay or pokemongo, my bank app is fine most everything is good now, restoring the one app for me isn't any issue. Wasn't going to end up using micro-g at all most-likely was just going to use bitgapps and be bummed about it if I couldn't find some type of decent fix for this. I don't think I could have continued using hiddencore1.7 with the always on display issue, so I hope it helps out others who feel the same way. No bypass yet without xposed or root at least I'm aware of,  but I hope some wizards can whip something up. Maybe figure out how to use the spoofing signature trick both above apps use with just magisk, or build it in somehow without actually using xposed which would prevent the check.

**Comment by leekzz** [comment]
> 
> 
> > I did have to restore snapchat from Titanium still.
> 
> Ye I would like to use that as well again but I don't have a backup...

I have a problem about this. I'm on LineageOS for MicroG 16.0 for OnePlus 6. When I restore my Snapchat backup with oandbackups or Titanium, it's not working.I launch Snapchat, I barely have time to see the camera that it instantly disconnects me from the app. Before it worked very well but since June it doesn't seem to work anymore and I didn't find anything similar on XDA. Do you guys have a fix for this?

**Comment by JohnGLFour** [comment]
I am using EdXpoaed, and trying to use the bypass safetynet.apk. Hope this worked

**Comment by JohnGLFour** [comment]
This worked on Magisk. I must say.

**Comment by ghost** [comment]
@leekzz Do you have Snapchat enabled in Magisk Hide (If you use Magisk obviously :D)

**Comment by ghost** [comment]
> This worked on Magisk. I must say.

And with apps that blocked you out before as well?

**Comment by leekzz** [comment]
@wilbie Yes he's activated, I'm using Magisk 19.4

**Comment by NotesOfReality** [comment]
> I am using EdXpoaed, and trying to use the bypass safetynet.apk. Hope this worked

I'm using Tai-Chi Xposed, would you please share the link of this APK and its thread/description/Git repo?
Do you happen to know if it should work on Tai-Chi Xposed too?
Would I have to use Magisk 19.4+ or should Magisk 19.3+ be ok?

**Comment by unresolvedsymbol** [comment]
I've acquired a successful safetynet request but the payload verification still fails so in total it means nothing to actual applications (Magisk manager doesn't verify the response as all other apps do). Tried both shady closed source safetynet bypass xposed modules with the SandHook variant of the Snapchat EdXposed fork (1.0.3 because I'm not on Q) & the original EdXposed. Tried stable as well as the last preview releases of droidguard. I'm using HavocOS 2.9 (Android 9.0) & Magisk v19.4 (also randomized manager package) on an LG-H872 (G6).

**Comment by bennofs** [comment]
@Nanolx do you know what the issue is? I would like to work on fixing this, but I am currently a bit lost where to look

**Comment by JohnGLFour** [comment]
The only solution is in 2 ways,
1. Make a 3rd party Saftynet that is the old version. (microG does allow to use other servers but building one needs time)
2. Rework to work with official SafetyNet.

**Comment by bennofs** [comment]
@JohnGLFour do you know what exactly changed? Also, can you even run your own SafetyNet? I would assume that attestations have to be signed by a private key that only google possesses.

**Comment by JohnGLFour** [comment]
From June to now it is 6 months, I still hope to see that this gets resolved soon.

**Comment by Nanolx** [comment]
It will be fixed eventually, @mar-v-in already ensured that, though no ETA and not highest priority, there are more important things to fix/support in first place (maps, login/auth, firebase support, etc.).

**Comment by Kreyren** [comment]
@ThibG Do you have any tracking to what is causing this issue so that I don't have to start form the scratch assuming this being a help-wanted issue?

**Comment by ClearlyClaire** [comment]
No, unfortunately, I don't

**Comment by sprainbrains** [comment]
> It will be fixed eventually, @mar-v-in already ensured that, though no ETA and not highest priority, there are more important things to fix/support in first place (maps, login/auth, firebase support, etc.).

good news. But what about the deadlines?

**Comment by Nanolx** [comment]
What deadlines?

Am 14. Februar 2020 15:16:05 MEZ schrieb Nikolai Sinyov <notifications@github.com>:
>> It will be fixed eventually, @mar-v-in already ensured that, though no ETA and not highest priority, there are more important things to fix/support in first place (maps, login/auth, firebase support, etc.).
>
>good news. But what about the deadlines?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/microg/android_packages_apps_RemoteDroidGuard/issues/24#issuecomment-586306236
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by axelsimon** [comment]
>  But what about the deadlines?

"No ETA" means no deadlines, @sprainbrains.
The message you quote gives you all the answers you need: it will be fixed eventually, no ETA, not highest priority. In other words, don't ask when it will be done.

**Comment by sprainbrains** [comment]
> What deadlines? Am 14. Februar 2020 15:16:05 MEZ schrieb Nikolai Sinyov <notifications@github.com>:
> > It will be fixed eventually, @mar-v-in already ensured that, though no ETA and not highest priority, there are more important things to fix/support in first place (maps, login/auth, firebase support, etc.). good news. But what about the deadlines? -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#24 (comment)](https://github.com/microg/android_packages_apps_RemoteDroidGuard/issues/24#issuecomment-586306236)
> -- Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.



> > But what about the deadlines?
> 
> "No ETA" means no deadlines, @sprainbrains.
> The message you quote gives you all the answers you need: it will be fixed eventually, no ETA, not highest priority. In other words, don't ask when it will be done.

Oh, sorry for my quuestion. I got it.
I'll be waiting.

**Comment by jeroenev** [comment]
It might become even harder to fix this, if not impossible:
"Magisk may no longer be able to hide bootloader unlocking from apps" https://www.xda-developers.com/magisk-no-longer-hide-bootloader-unlock-status/

**Comment by mid-kid** [comment]
:iphone: :gun:
Just kill it. Kill all of it. I am so done with this shit. If not having nice things is their way of welcoming potential users then so be it.

**Comment by theo546** [comment]
This move from Google prove us once again that we don't even the right to run whatever we want on our devices that we paid for (hence the weird stuff SafetyNet does to verify the device status).
I don't get how my Android phone is any less secure than my computer?
Applications are sandboxed on Android, not under Windows, so why should a banking app block a rooted device (considering rooting is not something anybody can do), instead of my big, more vulnerable PC? It just doesn't make any sense...

I'm now OK with not running apps that would require me to uninstall Magisk and use the Google Play Services. Fuck the apps that use SafetyNet and fuck Google, they are **not** getting on my phone.
I now understand why this issue was not fixed earlier. This is just a cat 'n mouse game.
Anyway, this was a little bit off-topic, but I'm glad nobody worked on this issue, in the end, it's a huge middle finger from Google.

**Comment by skid9000** [comment]
Off-topic too but all theses moves from Google and the fact that now they want to modulate Android with packages that you have to download from the PlayStore instead of the "old" OTA system is freaking me out... 
What's next ? All apps from the PlayStore should use SafetyNet ? Banning google accounts that have a rooted/flashed device linked to it ? Ban the device from the PlayStore at the hardware id level ?
At some point, we won't be able to run an up to date Android without Google's proprietary garbage or flash any alternative rom at all due to Google moves.

I'm not impacted much by SafetyNet (my banking app only check root) but yeah that's a middle finger from Google for ya.

**Comment by Gigadoc2** [comment]
> I don't get how my Android phone is any less secure than my computer?
> Applications are sandboxed on Android, not under Windows, so why should a banking app block a rooted device (considering rooting is not something anybody can do), instead of my big, more vulnerable PC? It just doesn't make any sense...

I clam the opposite: Your PC is less vulnerable than the average Android phone, because your PC receives most of the critical updates through Windows Update (or your Linux package manager), while with your phone most of the stuff still needs to go through the OEM who has no financial motivation to actually push those updates through (one might even say the opposite). On a PC, the only thing that is not kept up to date is BIOS firmware, and even that sometimes comes through Windows Update.

But then, banks (and the EU), insurers and more seem to claim that smartphones are more secure, as more and more stuff moves into being "App only". And then SafetyNet prevents you from keeping your phone up to date, which would have been the only thing making your phone actually more secure.

I think what is happening here is that a lot of people a) take end users to be very stupid (there is a point to that, but you can't prevent stupidity through technical measures) and b) think that locking down hardware and adding secure enclaves nets more security than timely updates. Unfortunately I don't have any credentials backing me, but I am very sure that timely updates are more important than locked-down and isolated hardware, in the grand scheme of things. Internally, Google probably knows this (as in, their security engineers know this), but they are obviously a bit biased to favour their Ecosystem over others, so they probably handwave the concerns away with "customers should just buy up-to-date hardware and everything would be fine".

**Comment by theo546** [comment]
I think you misunderstood, I was saying that my Android phone was claimed to be "unsecure" by banking apps and SafetyNet just because it doesn't pass this stupid test, while on my computer, I have no test to pass BUT I still can access my bank website, it just doesn't make any sense.
I gotta agree with you that OEM are lazy to react and patch security issues, but literally any process on your PC can read another process memory without any issues, there is good and bad in both sides.

**Comment by smnthermes** [comment]
> Applications are sandboxed on Android, not under Windows

Native applications aren't sandboxed on Windows, but websites are sandboxed on browsers.

**Comment by mimi89999** [comment]
How many apps are affected actually? Is anything besides Snapchat and several banking apps using SafetyNet?

**Comment by jeroenev** [comment]
Mcdonalds app, pokemon Go, Bancontact (the main mobile payment app used in my country), google pay.

**Comment by skid9000** [comment]
com.md.macdonalds.gomcdo ? I still have it on my phone and it seems to work fine without SafetyNet 🤔

**Comment by 532910** [comment]
google pay!

**Comment by ghost** [comment]
Yuka 

Le 29 avril 2020 13:38:30 GMT+02:00, sergio <notifications@github.com> a écrit :
>google pay!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/microg/android_packages_apps_RemoteDroidGuard/issues/24#issuecomment-621146656
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by 0x5ECF4ULT** [comment]
@errorcodevortex I reverse engineered the app you provided a download link to (was an early version of NoDeviceCheck over [here](https://github.com/pylerSM/NoDeviceCheck)) as well as the other "safetynet bypasses" in the XPosed repo. All of them are harmless (do not send any data, etc). All they do is block specific paths (eg su, xposed) and return true for basicIntegrity and ctsProfileMatch. This may lead to letting you login to apps that doesn't check the signature provided in the JWT response. But apps that check the signature on their own server/app like Snapchat, Netflix, banking apps and probably some others will see that the response has been tampered with.

**Comment by HanabishiRecca** [comment]
According to recent news: just forget about it. If you are not playing by Google rules you will not be able to pass SafetyNet. That's it.
https://www.xda-developers.com/safetynet-hardware-attestation-hide-root-magisk/

**Comment by sprainbrains** [comment]
> According to recent news: just forget about it. If you are not playing by Google rules you will not be able to pass SafetyNet. That's it.
> 
> https://www.xda-developers.com/safetynet-hardware-attestation-hide-root-magisk/

It’s a very sad news ( Well... we will live with this

**Comment by 0x5ECF4ULT** [comment]
Alrighty then we'll need a hardware hacker that gets the hardware attestation keys... But to my knowledge this hardware attestation thingy is nothing more than future dreams. This will go in prod in 2 years earliest but then then 99% of Android users will be mad at Google for blocking out legit, unmodified phones. That 1% are those people which change their phone every 2 years. IMO SN with forced hardware attestation will be a thing in 10+ years

**Comment by axelsimon** [comment]
> Alrighty then we'll need a hardware hacker that gets the hardware attestation keys...

Just to be clear, you are suggesting someone decap a SoC on a phone, and use an electron microscope to get that SoC's private key?

Also, i'm not sure you realise that the private key is not shared between devices, but unique to each chip. They are part of a chain of trust that goes back up to the manufacturer's root certificate. So even if you get one from one device, that does nothing for all the other devices. This is by design.

From [the documentation](https://developer.android.com/training/articles/security-key-attestation):
> If the device supports hardware-level key attestation, the root certificate within this chain is signed using an attestation root key, which the device manufacturer injects into the device's hardware-backed keystore at the factory.

So no, you don't just need "a hardware hacker that gets the hardware attestation keys", you need to either get the root certificate, at the end of the certificate chain, or to break that SoC's implementation of TrustZone, which is what is used on Android devices so far.

This says nothing of the future, where TrustZone is likely to be replaced by something better designed, that will incorporate the lessons of these past few years (Intel's SGX has suffered quite a few blows, you can imagine Google and ARM will not want to replicate that).

I'm quite curious as to why you think this "hardware attestation thingy is nothing more than future dreams", it's actually well under way and unlikely to not be in most devices in the near future.

Also, where do you get the stat that 1% of people change their phone every 2 years? In Europe, for instance, the average lifespan of a device is 21,6 months, in the USA 22.7 months (stats from 2016).

**Comment by 0x5ECF4ULT** [comment]
@axelsimon I apologize. Maybe I've been writing stuff before drinking my coffee.
I've opened a PR that works in the emulator. I hope those changes will be sufficient for the time until Google enforces hardware-backed attestation.

**Comment by ArchangeGabriel** [comment]
Can we get an APK build from the latest tag? I can’t find it in the microG F-Droid repo.

**Comment by Nanolx** [comment]
I made a build, feel free to give it a try. Of course it's got a different signature than the original, so first uninstall the official build (if any).

* https://nanolx.org/fdroid/repo/DroidGuard_0.apk

**Comment by tpaniaki** [comment]
> I made a build, feel free to give it a try. Of course it's got a different signature than the original, so first uninstall the official build (if any).
> 
> * https://nanolx.org/fdroid/repo/DroidGuard_0.apk

In my case (MicroG 0.2.10.19240-dirty with root / Magisk hide) still `Response payload validation failed`.

**Comment by 0x5ECF4ULT** [comment]
@jfk88 please follow #29 and #30 for clarification

**Comment by mtthidoteu** [comment]
> > I made a build, feel free to give it a try. Of course it's got a different signature than the original, so first uninstall the official build (if any).
> > 
> > * https://nanolx.org/fdroid/repo/DroidGuard_0.apk
> 
> In my case (MicroG 0.2.10.19240-dirty with root / Magisk hide) still `Response payload validation failed`.



> @jfk88 please follow #29 and #30 for clarification

Installed the last one @Nanolx replied with two days ago, and I'm getting that same error. What exactly are the steps to fix it (If, like i understood, it's working again)? Thanks

**Comment by 0x5ECF4ULT** [comment]
@mat789456 yep you're right. SN seems to be working again (at least Google signs the response). The only issue left is that the apk hashes aren't included in the payload which causes the request to fail. Stay tuned!

**Comment by BugGlitchy64** [comment]
Wow the progress so far! I'm still waiting tho.

**Comment by 0x5ECF4ULT** [comment]
@CRTComputer thanks for the feedback. Unfortunately I currently don't have time to continue the development of the fix. Watch #30 for updates.

**Comment by Funatiker** [comment]
> @CRTComputer thanks for the feedback. Unfortunately I currently don't have time to continue the development of the fix. Watch #30 for updates.

@0x5ECF4ULT I added some lines from a log file to the comments of that log file. I hope, it was the right place.

**Comment by werdahias** [comment]
I recently did a full reinstall of LOS 17.1 , but SN fails of course. Is there anything I can do to help debugging? Or has Google hardened the validation, making it impossible to pass?

**Comment by unresolvedsymbol** [comment]
No, this sandbox hasn't been updated for the new DroidGuard. If you want to pass SafetyNet install pico gapps, I'd assume you don't care about your privacy anyway if you're using a proprietary app that validates this.

**Comment by werdahias** [comment]
I do care about privacy, or else I wouldn't be using Lineage in the first place. I have three apps that require SN. It would be great if I could run these.

**Comment by Master0ne** [comment]
@CountOmega can you name those three apps? I am using several "critical" banking apps that need Magisk Hiding, but I have not come across an app that requires SafetyNet so far.

**Comment by 0x5ECF4ULT** [comment]
@CountOmega thanks for your offer, but unfortunately there's nothing where debugging could be of help. The main and (hopefully) only issue atm is that DroidGuardHelper (the sandbox DroidGuard runs in) doesn't return values that are signed by Google. Please watch #30 for updates.
For the hardening part: Google implemented key-vault-based (TPM, SE, ...) attestation which could prevent users with unlocked devices to pass SN in the future. However, this is not enforced yet. YMMV but it's only a matter of time IMO. Atm you can force BASIC attestation which is software based and not guarded by a key-vault.

**Comment by 0x5ECF4ULT** [comment]
@unresolvedsymbol in fact it has been updated. Please watch #29 and #30.

**Comment by werdahias** [comment]
Thank you for your explanation what the current state of things is. I already read about #29 and #30. I also installed @Nanolx' build of DroidGuard but I still get an error. If I need SN, should I just install pico Gapps atm? I really appriciate all the work you have done.

**Comment by 0x5ECF4ULT** [comment]
@CountOmega pico GApps are the better idea atm. Thanks for your kind words but it has not only been me. Marvin has been a huge help on my way there ;)

**Comment by werdahias** [comment]
Ok, thank you. I will reinstall Lineage with PicoGapps. Keep up the good work.

**Comment by ladislavkrivy** [comment]
@CountOmega If you have time to spare there is one thing worth trying. Some apps only check safetynet during first login/initialization so after doing that you can reboot, back them up, flash clean rom, restore and hope they keep working. (Make sure to magisk hide and hide magisk on the new rom too, not to trip some system checks. After some trip-up I was able to restore from backup again and the app luckily kept working, even survived some updates.)

**Comment by werdahias** [comment]
So did a reset and voilá, it works. CTS profile match is still false, but all relevant stuff seems to work.

**Comment by unresolvedsymbol** [comment]
@0x5ECF4ULT I've reviewed some of the last commits, however, are you sure the DroidGuard binary hasn't received any updates since July? GPS certainly has received many. I'd also say the result not being signed is a very critical flaw, and would result in any app with a proper SN implementation to disregard if the so called CTS profile and basic integrity were true. (Magisk Manager doesn't show this)

@CountOmega Tried clearing GPS (Google Play Services) data and restart the app you're testing SN with?

**Comment by 0x5ECF4ULT** [comment]
@unresolvedsymbol Yes the DG binary hasn't been updated since July but there's also a 1/10 chance that this binary gets invoked. The binary you mean is the offline DG. For online signage by Google the newest binary is downloaded and directly invoked. For the signage part: please take a good look at all the logcat outputs in the PRs. Google signs the requests. The only issue is that the response is not handed down to the app which requested the signage.

**Comment by mcdoe** [comment]
@0x5ECF4ULT are you passing SN w this?

**Comment by 0x5ECF4ULT** [comment]
@mcdoe I got indicators that Google sends back signed responses (no response was the original problem) but I'm not passing SN yet. First because I'm using an emulator and second because the code isn't fully functional yet.

**Comment by mcdoe** [comment]
@0x5ECF4ULT  got it. As far as you know, is there a way to pentest android apps in an emulator while passing safetynet?

**Comment by 0x5ECF4ULT** [comment]
@mcdoe no there's no way to achieve that using mG. You can try to install something like OpenGApps and fake your device properties to get CTS passing. Another method would be to mock everything using Frida and pray for the app to not verify the signature by phoning home.

**Comment by unresolvedsymbol** [comment]
Lately I've been using microG with apps that I thought(?) verified safetynet like snapchat, my banking apps, cashapp, revoult, etc without issues on 0.2.17.204714 with magiskhide enabled on said apps. Make of it what you will. 
![Screenshot_20210412-135207_SafetyNet_`attest`](https://user-images.githubusercontent.com/48220091/114445971-0c070e00-9c14-11eb-914b-a0bfb537d750.png)
![Screenshot_20210412-135233_microG_Services_Core](https://user-images.githubusercontent.com/48220091/114446018-188b6680-9c14-11eb-9a75-b8b9f32c1664.png)

**Comment by 0x5ECF4ULT** [comment]
That's weird. The only reason this could have happened is by authenticating to said apps prior to installing mG. What's your device?

**Comment by unresolvedsymbol** [comment]
> That's weird. The only reason this could have happened is by authenticating to said apps prior to installing mG. What's your device?

Using crDroid 7.4(?) on a OnePlus 7 Pro, no trace of gapps at all. And no, I can re-login to all said apps just fine. I don't use titanium backup.

Also if it makes a difference I self build nanodroid's microG metapackage and install it from storage with Magisk.

**Comment by Master0ne** [comment]
@unresolvedsymbol I'm using quite some banking and other sensitive apps myself (including Revolut and Revolut Business) and none of these require SafetyNet to pass, only Magisk Hide. Even the overly annoying DKB TAN2go app can be tricked by "freezing" Magisk first and in fact I haven't come across any app that requires SafetyNet to pass so far.

BTW I'm using ArrowOS 11 with Magisk v22.1 and microG v0.2.18.204714 with `Google SafetyNet: Off`, but nonetheless I really would like to see that issue resolved, just in case.

**Comment by 0x5ECF4ULT** [comment]
@unresolvedsymbol also on crDroid here :D could you by any chance capture your logcat output while logging in to Snapchat for example? This could eventually help resolving your mystery and this issue overall.

**Comment by unresolvedsymbol** [comment]
@0x5ECF4ULT https://a.pomf.cat/bktmgu.7z nothing much interesting as far as I can tell. cleared data + relogged into snap with keepassdx magikeyboard (then stripped some stuff, probably missed some but eh)

**Comment by Nanolx** [comment]
Not all apps may using SafetyNet or some may have changed to accept api failures when request itself was sent succesfully, because you know no recent Huawei device can attest SafetyNet, but those apps like Instagram, Snapchat & Co. still want those users' data/interactivity. Also there are some apps which only restrict certain functionality behind SN, like my banking app only dissallows fingerprint unlock or app-to-app tan, everything else works normally.

I don't know, it's just a wild guess.

**Comment by theo546** [comment]
So, this whole Huaweï trade ban thing may be a good thing for us after all, maybe we'll see more apps doing this, that can be a very nice solution.

**Comment by jeroenev** [comment]
Well, it might be
but the response from every single app from my country has been 
"we don't give a shit", "the market is too small", "we might re-evaluate in the future"

**Comment by jeroenev** [comment]
Huawei seems completely dead after the ban, you barely see any Huawei phones any more unless they're 2+ years old.
obviously in china they're still massive, but in Europe they seem completely dead.

**Comment by redchilis** [comment]
[![Safety Net](https://img.youtube.com/vi/LBBZeJhteRE/0.jpg)](https://www.youtube.com/watch?v=LBBZeJhteRE)

**Comment by kondors1995** [comment]
@unresolvedsymbol are you still able to use those apps after recent safey net changes since new changes broke CTS even for unrooted phones with costom rom

**Comment by OrionMoonclaw** [comment]
Considering that Google is trying to introduce hardware-based attestation and other companies are onto trusted computing again (Microsoft with AMD and Intel possibly?), maybe this should be closed? This never should've been an issue and its existence means we've failed. The proper way to fix everything here is standing up for your digital rights, do as much to distance yourselves from anything related to TC and push for legislation that will ban mechanisms such as this one.

**Comment by jeroenev** [comment]
hardware attestation is not enforced, and for many devices it might never be enforced because of hardware constraints, so it might make sense to fix this for the time being, though I doubt anyone is actually still spending time on this as it's been an issue for over 2 years now

**Comment by ale5000-git** [comment]
Fixed with latest microG GmsCore.

**Comment by kondors1995** [comment]
> Fixed with latest microG GmsCore.

whait wat?

**Comment by 0x5ECF4ULT** [comment]
> > Fixed with latest microG GmsCore.
> 
> whait wat?

Same. What?

**Comment by ale5000-git** [comment]
microG GmsCore 0.2.23.214816

**Comment by Atemu** [comment]
https://github.com/microg/GmsCore/releases/tag/v0.2.23.214816

**Comment by jeroenev** [comment]
Does it pass both basic integrity and cts checks? If yes it might finally be time for me to switch to microG again

**Comment by kondors1995** [comment]
> microG GmsCore 0.2.23.214816

so no need for RemoteDroidGuard apk

**Comment by 0x5ECF4ULT** [comment]
![this is fucking bonkers](https://user-images.githubusercontent.com/17967646/151158497-5fa95631-3969-411f-b1bf-1e51a37f26a1.png)
This is fucking bonkers. 

OP6T
crDroid 7.13
Rooted etc.
