### ISSUE TITLE
Hide unlocked bootloader

### ISSUE THREAD

**Issue by ale5000-git** [microg/RemoteDroidGuard#5]
Is it possible to do the same as done in [this change](https://github.com/sultanxda/android_kernel_oneplus_msm8996/commit/abc05b16bbd33521c2fffaf491c5657a94bfcfc5) but without change the ROM?

**Comment by mar-v-in** [comment]
I decided to not go into the details of tricking droidguard into anything, because it will be a mostly useless cat-and-mouse-game. If someone is willing to such a thing, it's up to them. As with other contributions that are about spoofing, I will keep the corresponding pull requests open, so that you can easily find it.
